### PR TITLE
Added TimeGrain and Duration Dimensions to Russian language

### PR DESCRIPTION
**Pull request by igor-drozdov**
- Added Duration dimension to Russian language
- Added TimeGrain dimension to Russian language
- Refactored isNatural and isNaturalWith out of Duration helpers into Numeral helpers
- Implemented <integer> and a half rule for Russian Numeral
- Changed the type of inSeconds to polymorphic one

### CODE REVIEW

**Comment by patapizza** [comment]
Thanks @igor-drozdov! Awesome work!
Ready for `Time`? ;-)

Regarding `rulePositiveDuration` we might need to revisit to round to the highest possible grain. (e.g. when I write `1.5 years` I expect `18 months`, not `47300000 seconds`).

**Comment by igor-drozdov** [comment]
@patapizza yea, `Time` is probably the next :)

I agree, `1.5 years` as `18 months` is more intuitive than seconds. I even started to implement a function which represented a grain by lower ones, so that it could be multiplied by a double, but decided not to overcomplicate things at the moment. But yea, that a nice point to revisit.

By the way, is the presence of lower grains the reason why `DurationData`'s `value` is of `Int` type?

**Comment by patapizza** [comment]
Awesome! Looking forward to it 👍 

Yeah, that would be a nice follow up. 

The value for `Duration` is because we didn't really see a use case for a more precise type.

**Comment by chessai** [comment]
> Any news about Time?!

Time is in now :)

**Pull request closed without merging**
