### PR TITLE
Add support for Ordinal, Quantity, & Temperature dimension for KM.

### PR DESCRIPTION
**Pull request by pheaktra21**
Hello. 
I added 3 new dimensions: Ordinal, Quantity, & Temperature. And I also added more data to Numeral dimension.
Thank you!

### CODE REVIEW

**Comment by pheaktra21** [comment]
I would appreciate if there is someone taking a look at this issue at soon as possible.

**Comment by pheaktra21** [comment]
I would appreciate if there is someone taking a look at this issue as soon as possible.

**Comment by patapizza** [comment]
សូមអរគុណ @pheaktra21!

I've removed the custom units for `Quantity` as persons, buildings, foods etc aren't generally considered as units (as opposed to e.g. feet, meters, cups).

**Comment by pheaktra21** [comment]
Okay. Thank you very much @patapizza !
I'll work on adding more data to it. :)

**Comment by pheaktra21** [comment]
Sorry @patapizza.
After the second thought, I think I really need to add those units back. Different from English, Khmer language has units for various things such as persons, animals, trees, flowers, and buildings. They have similar use to the Cups.
What do you think about this?

**Comment by patapizza** [comment]
I'm not familiar with Khmer - how many unit types do you have? Feel free to re-submit a pull request, sorry about that.

**Comment by pheaktra21** [comment]
There are too many of quantity units. I can barely know them all. However, I'll try to add as many as I remember.

**Pull request closed without merging**
