### PR TITLE
Mongolian

### PR DESCRIPTION
**Pull request by uugan**
MN Setup+Numeral

### CODE REVIEW

**Comment by uugan** [comment]
travis gives error like:
```
tests/Duckling/Temperature/MN/Tests.hs:17:1: error:
    Failed to load interface for ‘Duckling.Temperature.MN.Corpus’
    Perhaps you meant
      Duckling.Temperature.EN.Corpus (from duckling-0.1.6.1)
      Duckling.Temperature.AR.Corpus (from duckling-0.1.6.1)
      Duckling.Temperature.ES.Corpus (from duckling-0.1.6.1)
    Use -v to see a list of the files searched for.
```
who knows what is wrong with my commit?

**Comment by uugan** [comment]
@patapizza now its final. Please merge my pull request.

**Comment by patapizza** [comment]
Thank you @uugan!

**Comment by uugan** [comment]
@patapizza You're welcome :) Is that possible to add MN (language) to https://duckling.wit.ai/ ?

**Comment by patapizza** [comment]
@uugan duckling.wit.ai is out of date and is still running the legacy Clojure library - we'll incorporate Mongolian once we find the cycles to upgrade it.

**Pull request closed without merging**
