### PR TITLE
Catalan Language. Test Failures

### PR DESCRIPTION
**Pull request by leandroPGC**
First commit of Catalan Language. Includes dimensions:

- AmountOfMoney
- Distance
- Duration
- Numeral
- Ordinal
- Temperature
- Time
- Volume

@XavierPlaza

### CODE REVIEW

**Comment by chessai** [comment]
@leandroPGC Please rebase on top of `master` to get new GitHub CI configuration.

**Comment by chessai** [comment]
@leandroPGC looks like you're using ES locale in some places instead of CA, also CA in some places is Canada (the region). 

Additionally, this PR is pretty massive, making it hard to review. Typically we prefer if PRs are split along dimension boundaries - e.g. one for Numeral, one for Time, one for... etc. If you could split this up that would be good.

**Comment by leandroPGC** [comment]
@chessai

Yes, we are using ES locale since Catalunya is an autonomous community of Spain and we have followed the ISO 3166-1 alpha-2 country code used in the file ```Duckling/Region.hs```.

As you mention, CA stands for (region) Canada. However, according to ISO 639-1 codes _ca_ represents Catalan, which forced us to modify the language/region mapping in the file '''Duckling/Locale.hs''' as follows:

```
import qualified Duckling.Region as R
  ( Region
      ( AR
      , CA
      , ES
      , NL
      )
  )

allLocales :: HashMap Lang (HashSet Region)
allLocales =
  HashMap.fromList
    [ (CA, HashSet.fromList [R.ES])
    , (EN, HashSet.fromList [AU, BZ, R.CA, GB, IN, IE, JM, NZ, PH, ZA, TT, US])
    , (ES, HashSet.fromList [R.AR, CL, CO, R.ES, MX, PE, VE])
    , (NL, HashSet.fromList [BE, R.NL])
    , (ZH, HashSet.fromList [CN, HK, MO, TW])
    ]
```
As far as we understand, this way we have mapped CA (Catalan) to ES (region) and defined R.CA as Canada (region). A similar situation happens, for example, with AR as arabic language and AR as Argentina (region), where the same code represents both a language and a region (locale).

On the other hand, we have successfully debugged all the dimensions but Time, which we are currently fixing.

As you requested, we will split along dimensions for future PRs.

Thanks!

**Comment by chessai** [comment]
@leandroPGC FYI I have gotten Numeral and Ordinal in. Working on getting the rest in slowly.

**Comment by leandroPGC** [comment]
@chessai thanks for the update!

**Comment by chessai** [comment]
All work merged in 79078121840587c6f34080b6e4cdfc939f73e7d0, f3e128a07b6c0dcea7f4e5b7abb85cbdae5f85bb, 213d1f12a5671f2a59f76e359f4321cc7d91a746, 1322cd69ec91cebe310fe187c5c771c706d7959a, 219e5600d64302fc25c169aeaf8c2dd4bdb97116, 0e3d0604a2182f183633042d94af3f7fcb5baec1, f10c4db1128a201cc8876255d51cfb0b90f228b5, 173d8c235fca5b48ba3a517c18067effc01b2950, and 5d8d99bbf40ec76931f3efc6b7e63d5aefda0014

**Pull request closed without merging**
