### PR TITLE
fix Valentine's Day regex in arabic

### PR DESCRIPTION
**Pull request by Abdallatif**

### CODE REVIEW

**Comment by adelnobel** [comment]
@Abdallatif Can you please provide a summary on what this fixes? Also, can you add the test case to the test files?

**Comment by Abdallatif** [comment]
Hi @adelnobel, Sorry for not providing summery, I thought the title was enough. The word 'حب' which mean love was recognized as Valentine's Day (false positive). There should be 'عيد' or 'يوم' before it.
I don't know how we should test false positive examples?

**Comment by adelnobel** [comment]
Gotcha, thanks for the explanation. You can add false negative tests as in here 

https://github.com/facebook/duckling/blob/master/Duckling/Time/EN/Corpus.hs#L71

**Comment by patapizza** [comment]
To be clear, you'd have to implement a negative corpus for the Arabic `Time`.

**Pull request closed without merging**
