### PR TITLE
Add Volume/KM, Time/KM, and Distance/KM

### PR DESCRIPTION
**Pull request by pheaktra21**
Hello.
I have updated Quantity/KM and added 3 more dimensions (Volume/KM, Time/KM, and Distance/KM) for KM.
Please take a look at it.

### CODE REVIEW

**Comment by pheaktra21** [comment]
Hello.
I have added this pull request for almost 4 weeks, but it still hasn't been merged yet.
Is there any problem that I can fix?
Thanks!

**Comment by xhavokx** [comment]
Hi pheaktra21. The delay is entirely down to my lack of time. For the most part the PR is great. I'm going to take out the Time implementation, and ask if you can submit a separate PR for Time, TimeGrain and Duration?
I'll merge this PR with master as soon as I'm able to. Thank you for your patience.

**Comment by pheaktra21** [comment]
Thank you @xhavokx . I'll submit another PR for TimeGrain, Time, and Duration. :)

**Comment by xhavokx** [comment]
@pheaktra21, your PR has been accepted. Thanks for the great work!

**Comment by pheaktra21** [comment]
> @pheaktra21, your PR has been accepted. Thanks for the great work!

Thank you so much @xhavokx

**Pull request closed without merging**
