### PR TITLE
Added TimeGrain to Hindi (HI)

### PR DESCRIPTION
**Pull request by anshuman23**
I have added __TimeGrain__ support to __Hindi (HI)__. Please let me know if there are any other changes required!

Cheers! :)

### CODE REVIEW

**Comment by anshuman23** [comment]
Why is the build failing for GHC 8.0.2 but not GHC 8.2.1?

It seems that there was a timeout of some sort and that is why it failed? It builds fine for me locally so if someone could let me know how to fix this, I'll make the necessary changes

**Comment by anshuman23** [comment]
@chinmay87 Any changes to be made to get Travis to pass for GHC 8.0.2?

**Comment by chinmay87** [comment]
@anshuman23 -  Looks like a transient issue. Merging in the PR now!

**Comment by anshuman23** [comment]
Awesome! That's good to know :)

**Comment by chinmay87** [comment]
Thanks again @anshuman23 :)

**Pull request closed without merging**
