### PR TITLE
Adding missing Dimensions.SW to duckling.cabal

### PR DESCRIPTION
**Pull request by annesylvie**

### CODE REVIEW

**Comment by cowjen01** [comment]
Hello, I had the same issue two days ago. Checkout [my pull request](https://github.com/facebook/duckling/pull/317). I was trying to fix the same problem.

**Comment by annesylvie** [comment]
@cowjen01 Indeed! Thanks for pointing this out, I didn't notice. Why did you close your PR? It is not merged yet. Is it because of the failing build?
It works for me locally, so I'm good for now, but would be good to have that line added to the codebase.

**Comment by cowjen01** [comment]
@annesylvie Yes, I've closed it because the second build has failed. I thought I should investigate the issue locally before I open the pull request again, but I didn't find anything. It works for me as well.

**Comment by imadcat** [comment]
I have the exact same problem building it, and adding ", Dimensions.SW" to duckling.cabal solved it.

**Comment by chinmay87** [comment]
Thanks @annesylvie and @cowjen01 for the fix!!

**Pull request closed without merging**
